---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
projects <- read_delim("../data/projects.csv", 
    ",", escape_double = FALSE, trim_ws = TRUE)
colnames(projects) <- c("G", "A", "RepoUrl", "Dataset", "Cloned", "LastCommitDate", "Commits", "Branches", "Tags", "Committers", "CommitID", "RootPOM", "Compile", "Test1", "Tests", "Test2")

languages <-read_delim("../data/languages.csv", 
    ",", escape_double = FALSE, trim_ws = TRUE, col_names = FALSE)

colnames(languages) <- c("G" ,"A", "Files", "Lang", "BlankLines", "Comments", "CodeLines")
```

```{r}


as.factor(languages$Lang) %>% summary()

major_lang <- c("Markdown","Java","Maven","YAML","XML","JSON","JavaScript","HTML","BourneShell","DOSBatch","Groovy","CSS","BourneAgainShell","Scala","ProGuard","TypeScript","make","SQL","XSD","Kotlin","Python","Ant","Sass","AsciiDoc","Dockerfile","VelocityTemplateLanguage","JSP","XSLT")

```


```{r}
nb_p <- languages %>% select(G,A) %>% distinct() %>% count()
cleannbp <- nb_p$n[1]

langDistrib <- languages %>%
  select(Lang) %>% 
  filter(Lang %in% major_lang) %>% 
  group_by(Lang) %>%
  count() %>% 
  ungroup() %>% 
  mutate(perc = 100 * n / cleannbp) %>% 
  mutate(type = ifelse(Lang == "Java" | Lang == "Groovy" | Lang == "Scala" | Lang == "Kotlin", "JVM", "Non JVM")) %>% 
  ggplot(aes(x = reorder(Lang, perc), y = perc, fill = type)) + 
  geom_bar(width = 0.75, stat = "identity") +
  labs(x = "Language", y = "% Projects") + 
  coord_flip() +
  theme(legend.title=element_blank())

langDistrib

ggsave(filename = "langDistrib.png", device="png", height = 6, width = 8,  units = c("in"))
```

```{r}
docker_user <- languages %>% filter(Lang == "Dockerfile") %>% select(G,A) %>% merge(y = projects, by.x = c("G", "A"), by.y = c("G", "A")) %>% filter(Compile == "true")
```

```{r}
write.csv(docker_user, file = "../data/observability.csv")
```

```{r}
languages %>% group_by(G,A) %>% summarise(f = sum(Files), b = sum(BlankLines), com = sum(Comments), loc = sum(CodeLines)) %>% summary()

sum(languages$Files)
sum(languages$CodeLines)

```
